<?php

namespace App\Models;

class AiFeeds implements FeedsListInterface
{
    public function getFeeds()
    {
        return [
            [
                'label' => 'Websites',
                'slug' => 'websites',
                'feeds' => [
                    //  [
                    //     'label'       => '',
                    //     'slug'        => '',
                    //     'url'         => '',
                    //     'description' => '',
                    //     'website'     => '',
                    //     'facebook'    => '',
                    //     'twitter'     => '',
                    //     'linkedin'    => '',
                    //     'youtube'     => '',
                    //     'github'      => '',
                    //     'keywords'    => '',
                    //     'og_image'    => '',
                    // ],
                     [
                        'label'       => 'Machine learning mastery',
                        'slug'        => 'maschine-learning-mastery',
                        'url'         => 'https://machinelearningmastery.com/blog/feed/',
                        'description' => 'Machine Learning Mastery Blog',
                        'website'     => 'https://machinelearningmastery.com',
                        'facebook'    => 'https://www.facebook.com/MachineLearningMastery/',
                        'twitter'     => 'https://twitter.com/TeachTheMachine',
                        'linkedin'    => 'https://www.linkedin.com/company/machine-learning-mastery/',
                        'youtube'     => '',
                        'github'      => '',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                    [
                        'label'       => 'Open AI',
                        'slug'        => 'openai-blog',
                        'url'         => 'https://openai.com/news/rss.xml',
                        'description' => '',
                        'website'     => 'https://openai.com/news',
                        'facebook'    => '',
                        'twitter'     => 'https://x.com/OpenAI',
                        'linkedin'    => 'https://www.linkedin.com/company/openai',
                        'youtube'     => 'https://www.youtube.com/OpenAI',
                        'github'      => 'https://github.com/openai',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                    [
                        'label'       => 'MarkTechPost',
                        'slug'        => 'mark-tec-post',
                        'url'         => 'https://www.marktechpost.com/feed/',
                        'description' => '',
                        'website'     => 'https://www.marktechpost.com/',
                        'facebook'    => '',
                        'twitter'     => 'https://twitter.com/Marktechpost',
                        'linkedin'    => 'https://www.linkedin.com/company/marktechpost/',
                        'youtube'     => '',
                        'github'      => '',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                    [
                        'label'       => 'Google Deepmind',
                        'slug'        => 'google-deepmind',
                        'url'         => 'https://deepmind.google/blog/rss.xml',
                        'description' => '',
                        'website'     => 'https://deepmind.google/',
                        'facebook'    => '',
                        'twitter'     => 'https://x.com/googledeepmind',
                        'linkedin'    => 'https://www.linkedin.com/company/googledeepmind/',
                        'youtube'     => '',
                        'github'      => '',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                    [
                        'label'       => 'Google research',
                        'slug'        => 'google-research',
                        'url'         => 'https://research.google/blog/rss/',
                        'description' => '',
                        'website'     => 'https://research.google/blog/',
                        'facebook'    => '',
                        'twitter'     => 'https://x.com/GoogleResearch',
                        'linkedin'    => 'https://www.linkedin.com/showcase/googleresearch/',
                        'youtube'     => 'https://www.youtube.com/c/GoogleResearch',
                        'github'      => 'https://github.com/google-research',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                    // https://www.unite.ai/feed/ feeds disabled :(
                    [
                        'label'       => 'Artificial-Intelligence blog',
                        'slug'        => 'artificial-intelligence-blog',
                        'url'         => 'https://www.artificial-intelligence.blog/ai-news?format=rss',
                        'description' => '',
                        'website'     => 'https://www.artificial-intelligence.blog',
                        'facebook'    => 'https://www.facebook.com/wwwAIblog',
                        'twitter'     => 'https://twitter.com/wwwAIblog',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                    [
                        'label'       => 'Ai2people',
                        'slug'        => 'ai-2-peple',
                        'url'         => 'https://ai2people.com/feed/',
                        'description' => '',
                        'website'     => 'https://ai2people.com/news/',
                        'facebook'    => 'https://www.facebook.com/Feedspot',
                        'twitter'     => 'https://www.twitter.com/_feedspot',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                    [
                        'label'       => 'TechSpective',
                        'slug'        => 'tech-spective',
                        'url'         => 'https://techspective.net/category/technology/artificial-intelligence/feed/',
                        'description' => '',
                        'website'     => 'https://techspective.net/category/technology/artificial-intelligence/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                    [
                        'label'       => 'Qudata',
                        'slug'        => 'qudata',
                        'url'         => 'https://qudata.com/en/news/rss.xml',
                        'description' => '',
                        'website'     => 'https://qudata.com/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => 'https://www.linkedin.com/company/qudata-ai/',
                        'youtube'     => 'https://www.youtube.com/c/Qudata',
                        'github'      => 'https://github.com/qudataai',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                    [
                        'label'       => 'MetaDevo AI Blog',
                        'slug'        => 'MetaDevo',
                        'url'         => 'https://qudata.com/en/news/rss.xml',
                        'description' => '',
                        'website'     => '',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                ]
            ]
        ];
    }
}
