<?php

namespace App\Models;

class CybersecurityFeeds implements FeedsListInterface
{
    public function getFeeds()
    {
        return [
            [
                'picture'       => 'threat-post.gif',
                'label'         => 'Threat Post',
                'description'   => 'Latest news from Threat Post',
                'slug'          => 'threat-post',
                'website'       => 'https://www.threatpost.com/',
                'youtube'       => 'https://www.youtube.com/user/threatpost',
                'facebook'      => 'https://www.facebook.com/Threatpost/',
                'twitter'       => 'https://twitter.com/threatpost/',
                'gplus'         => 'https://plus.google.com/103973344735603121561/posts',
                'linkedin'      => 'https://www.linkedin.com/groups/12103060',
                'feeds' => [
                    [
                        'label'         => 'Cloud Security',
                        'slug'          => 'threat-post-cloud-security',
                        'url'           => 'https://threatpost.com/category/cloud-security/feed',
                        'description'   => 'Cloud Security news on threat post',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Critical Infrastructure',
                        'slug'          => 'threat-post-critical-infrastructure',
                        'url'           => 'https://threatpost.com/category/critical-infrastructure/feed',
                        'description'   => 'Critical Infrastructure news on threat post',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Cryptography',
                        'slug'          => 'threat-post-cryptographye',
                        'url'           => 'https://threatpost.com/category/critical-infrastructure/feed',
                        'description'   => 'Cryptography news on threat post',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Government',
                        'slug'          => 'threat-post-government',
                        'url'           => 'https://threatpost.com/category/government/feed',
                        'description'   => 'Government news on Threat Post',
                        'keywords'      => 'internet of thigs,threat post,'.'',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Hacks',
                        'slug'          => 'threat-post-hacks',
                        'url'           => 'https://threatpost.com/category/hacks/feed',
                        'description'   => 'Threat post Hackings news',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'IoT',
                        'slug'          => 'threat-post-iot',
                        'url'           => 'https://threatpost.com/category/iot/feed',
                        'description'   => 'Threat post Internet of Things news',
                        'keywords'      => 'internet of thigs,feed,threat post,hacking,security',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Mobile Security',
                        'slug'          => 'threat-post-mobile-security',
                        'url'           => 'https://threatpost.com/category/mobile-security/feed',
                        'description'   => 'Threat post Mobile Security news',
                        'keywords'      => 'mobile,security,feed,threat post,hacking,cyber,security',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Privacy',
                        'slug'          => 'threat-post-privacy',
                        'url'           => 'https://threatpost.com/category/privacy/feed',
                        'description'   => 'Threat post Privacy news',
                        'keywords'      => 'privacy,feed,threat post,hacking,cyber,security',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Vulnerabilities',
                        'slug'          => 'threat-post-vulnerabilities',
                        'url'           => 'https://threatpost.com/category/vulnerabilities/feed',
                        'description'   => 'Threat post Vulnerabilities news',
                        'keywords'      => 'vulnerabilities,feed,threat post,hacking,cyber,security',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Web Security',
                        'slug'          => 'threat-post-web-security',
                        'url'           => 'https://threatpost.com/category/web-security/feed',
                        'description'   => 'Threat post Vulnerabilities news',
                        'keywords'      => 'web security,feed,threat post,hacking,cyber,security',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Videos',
                        'slug'          => 'threat-post-videos',
                        'url'           => 'https://threatpost.com/category/videos/feed',
                        'description'   => 'Threat post Videos',
                        'keywords'      => 'feed,threat post,hacking,cyber,security',
                        'og_image'      => '',
                    ],
                ]
            ],
            [
                'picture'               => 'cyber-security-websites.gif',
                'label'                 => 'Websites and Blogs',
                'description'           => 'The best information security news from the best websites and blogs',
                'slug'                  => 'websites',
                'feeds' => [
                    // Empty template
                    /*
                    [
                        'label'         => '',
                        'slug'          => '',
                        'url'           => '',
                        'description'   => '',
                        'website'       => '',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    */
                    [
                        'label'         => 'Dark reading',
                        'slug'          => 'dark-reading',
                        'url'           => 'https://www.darkreading.com/rss.xml',
                        'description'   => 'Dark Reading is now the most trusted online community for security professionals',
                        'website'       => 'https://www.darkreading.com/',
                        'facebook'      => 'https://www.facebook.com/darkreadingcom/',
                        'twitter'       => '',
                        'youtube'       => 'https://www.youtube.com/@DarkReadingOfficialYT',
                        'linkedin'      => 'https://www.linkedin.com/company/dark-reading/',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'The Hacker News',
                        'slug'          => 'the-hacker-news',
                        'url'           => 'http://feeds.feedburner.com/TheHackersNews?format=xml',
                        'description'   => 'The Hacker News has been internationally recognized as a leading news source dedicated to promoting awareness for security experts and hackers',
                        'website'       => 'https://thehackernews.com/',
                        'facebook'      => 'https://www.facebook.com/thehackernews',
                        'twitter'       => 'https://twitter.com/thehackersnews',
                        'youtube'       => 'https://www.youtube.com/user/hackernewsvideos?sub_confirmation=1',
                        'linkedin'      => 'https://www.linkedin.com/company/the-hacker-news/',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'EC Council',
                        'slug'          => 'ec-council',
                        'url'           => 'https://www.eccouncil.org/feed/',
                        'description'   => 'EC-Council\'s New Learning Track Launched Globally',
                        'website'       => 'https://www.eccouncil.org/',
                        'facebook'      => 'https://www.facebook.com/ECCouncil',
                        'twitter'       => 'https://twitter.com/ECCOUNCIL',
                        'youtube'       => 'https://www.youtube.com/user/eccouncilusa',
                        'linkedin'      => 'https://www.linkedin.com/company/ec-council',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    //    [
                    //         'label'         => 'Kali Linux',
                    //         'slug'          => 'kali-linux',
                    //         'url'           => 'https://www.kali.org/feed/',
                    //         'description'   => 'Kali Linux RSS Feed',
                    //         'website'       => 'https://www.kali.org/',
                    //         'facebook'      => '',
                    //         'twitter'       => 'https://twitter.com/kalilinux',
                    //         'youtube'       => '',
                    //         'linkedin'      => 'http://www.linkedin.com/groups?gid=970937',
                    //         'github'        => 'https://github.com/offensive-security',
                    //         'keywords'      => '',
                    //         'og_image'      => '',
                    //    ],
                    //    [
                    //        'label'         => 'Offensive Security',
                    //        'slug'          => 'offensive-security',
                    //        'url'           => 'https://www.offensive-security.com/feed/', // Returns error 403 Forbidden? Chekc the parser
                    //        'description'   => 'Offensive Security RSS Feed',
                    //        'website'       => 'https://www.offensive-security.com/',
                    //        'facebook'      => 'https://www.facebook.com/KaliLinux',
                    //        'twitter'       => 'https://twitter.com/offsectraining',
                    //        'linkedin'      => 'https://www.linkedin.com/company/ec-council',
                    //        'keywords'      => '',
                    //        'og_image'      => '',
                    //    ],
                    // [
                    //     'label'         => '',
                    //     'slug'          => '',
                    //     'url'           => '',
                    //     'description'   => '',
                    //     'website'       => '',
                    //     'facebook'      => '',
                    //     'twitter'       => '',
                    //     'youtube'       => '',
                    //     'linkedin'      => '',
                    //     'github'        => '',
                    //     'keywords'      => '',
                    //     'og_image'      => '',
                    // ],
                    [
                        'label'         => 'Naked Security',
                        'slug'          => 'naked-security',
                        'url'           => 'https://nakedsecurity.sophos.com/feed/',
                        'description'   => 'Naked Security RSS Feed',
                        'website'       => 'https://nakedsecurity.sophos.com/',
                        'facebook'      => 'https://www.facebook.com/SophosSecurity',
                        'twitter'       => 'https://twitter.com/#!/NakedSecurity',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/5053/',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Google Online Security Blog',
                        'slug'          => 'google-online',
                        'url'           => 'http://feeds.feedburner.com/GoogleOnlineSecurityBlog',
                        'description'   => 'Google Online Security Blog RSS Feed',
                        'website'       => 'https://security.googleblog.com/',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Security Affairs',
                        'slug'          => 'security-affairs',
                        'url'           => 'http://securityaffairs.co/wordpress/feed',
                        'description'   => 'Security Affairs RSS Feed',
                        'website'       => 'http://securityaffairs.co/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'E Hacking News',
                        'slug'          => 'ehacker-news',
                        'url'           => 'http://www.ehackingnews.com/feeds/posts/default?alt=rss',
                        'description'   => 'E Hacking News | Latest Hacker News and IT Security News RSS Feed',
                        'website'       => 'http://www.ehackingnews.com/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Security Week',
                        'slug'          => 'security-week',
                        'url'           => 'http://feeds.feedburner.com/Securityweek?format=xml',
                        'description'   => 'SecurityWeek | Information Security News, IT Security News & Expert Insights RSS Feed',
                        'website'       => 'http://www.securityweek.com/',
                        'facebook'      => 'https://www.facebook.com/SecurityWeekCom-366251913615/',
                        'twitter'       => 'https://twitter.com/securityweek',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/securityweek/',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Help Net Security',
                        'slug'          => 'help-net-security',
                        'url'           => 'https://www.helpnetsecurity.com/feed',
                        'description'   => 'Help Net Security RSS Feed',
                        'website'       => 'https://www.helpnetsecurity.com/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'HackRead',
                        'slug'          => 'hackread',
                        'url'           => 'https://www.hackread.com/feed',
                        'description'   => 'HackRead | Latest Cyber Crime - InfoSec - Tech - Hacking News RSS Feed',
                        'website'       => 'https://www.hackread.com/',
                        'facebook'      => 'https://facebook.com/HackRead',
                        'twitter'       => 'https://twitter.com/HackRead',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/10290450',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Search Security',
                        'slug'          => 'search-security',
                        'url'           => 'http://searchsecurity.techtarget.com/rss/Security-Wire-Daily-News.xml',
                        'description'   => 'SearchSecurity RSS Feed',
                        'website'       => 'https://searchsecurity.techtarget.com/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Comodo News',
                        'slug'          => 'comodo-news',
                        'url'           => 'https://posts.comodo.com/feed',
                        'description'   => 'Comodo News | Internet Security Information RSS Feed',
                        'website'       => 'https://posts.comodo.com',
                        'facebook'      => 'https://www.facebook.com/ComodoHome',
                        'twitter'       => 'https://twitter.com/comodo_labs',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Tech Worm',
                        'slug'          => 'techworm',
                        'url'           => 'https://www.techworm.net/feed',
                        'description'   => 'TechWorm RSS Feed',
                        'website'       => 'https://www.techworm.net/',
                        'facebook'      => 'https://www.facebook.com/techworm.in/',
                        'twitter'       => 'https://twitter.com/Techworm_in',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Techworld - Security',
                        'slug'          => 'techworld',
                        'url'           => 'http://www.techworld.com/security/rss',
                        'description'   => 'Techworld - Security RSS Feed',
                        'website'       => 'http://www.techworld.com/security/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Security Gladiators',
                        'slug'          => 'security-gladiators',
                        'url'           => 'https://securitygladiators.com/internet-security-news/feed',
                        'description'   => 'Security Gladiators - Internet Security News RSS Feed',
                        'website'       => 'https://securitygladiators.com/internet-security-news/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'GBHackers On Security',
                        'slug'          => 'gbhackers-on-security',
                        'url'           => 'https://gbhackers.com/feed/',
                        'description'   => 'GBHackers On Security RSS Feed',
                        'website'       => 'https://www.gbhackers.com/',
                        'facebook'      => '',
                        'twitter'       => 'https://twitter.com/gbhackers_news',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/cybersecurity-news/',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    // The Guardinan https://www.theguardian.com/technology/data-computer-security/rss | https://www.theguardian.com/technology/data-computer-security
                    // Data and computer security | The Guardian RSS Feed
                    // Forbes https://www.forbes.com/security/feed/ | http://www.forbes.com/security/index.xml
                    [
                        'label'         => 'Cisco Blog',
                        'slug'          => 'cisco-posts',
                        'url'           => 'http://blogs.cisco.com/category/security/feed/',
                        'description'   => 'Cisco Blog - Security RSS Feed',
                        'website'       => 'https://blogs.cisco.com/security',
                        'facebook'      => 'https://www.facebook.com/ciscosecurity?ref=nf',
                        'twitter'       => 'https://twitter.com/ciscosecurity',
                        'youtube'       => 'https://www.youtube.com/user/Cisco/playlists?shelf_id=5&sort=dd&view=50',
                        'linkedin'      => 'http://www.linkedin.com/company/cisco',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    // TechRepublic https://www.techrepublic.com/topic/security/ | http://www.techrepublic.com/rssfeeds/topic/security/?feedType=rssfeeds
                    // NIST NSTIC NOTES RSS Feed https://www.nist.gov/blogs/i-think-therefore-iam | https://www.nist.gov/blogs/i-think,-therefore-iam/rss.xml
                    [
                        'label'         => 'Zero Day | ZDNet',
                        'slug'          => 'zero-day-zdnetw',
                        'url'           => 'https://www.zdnet.com/posts/security/rss.xml',
                        'description'   => 'Zero Day | ZDNet RSS Feed',
                        'website'       => 'https://www.zdnet.com',
                        'facebook'      => 'https://www.facebook.com/pages/ZDNet/5953112932',
                        'twitter'       => 'http://twitter.com/zdnet',
                        'youtube'       => 'https://www.youtube.com/channel/UCr9QWb5RKLfaunjKHJZAdQQ',
                        'linkedin'      => 'https://www.linkedin.com/company/zdnet-com',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'TRUSTe Blog',
                        'slug'          => 'truste-posts',
                        'url'           => 'http://www.trustarc.com/posts/feed/',
                        'description'   => 'TRUSTe Blog RSS Feed',
                        'website'       => 'https://www.trustarc.com/posts/',
                        'facebook'      => 'https://www.facebook.com/TrustArc/',
                        'twitter'       => 'https://twitter.com/trustarc',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/21121',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Webroot Threat Blog',
                        'slug'          => 'webroot-threat-posts',
                        'url'           => 'https://www.webroot.com/posts/feed',
                        'description'   => 'Webroot Threat Blog RSS Feed',
                        'website'       => 'https://www.webroot.com/posts/',
                        'facebook'      => 'https://www.facebook.com/Webroot',
                        'twitter'       => 'https://twitter.com/Webroot',
                        'youtube'       => 'https://www.youtube.com/user/WebrootSoftware?sub_confirmation=1',
                        'linkedin'      => 'https://www.linkedin.com/company/7434',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Threat Insight Blog',
                        'slug'          => 'threat-insight',
                        'url'           => 'https://www.proofpoint.com/us/rss.xml',
                        'description'   => 'Threat Insight Blog - Cybersecurity Intelligence | Proofpoint',
                        'website'       => 'https://www.proofpoint.com/',
                        'facebook'      => 'http://www.facebook.com/proofpoint',
                        'twitter'       => 'http://www.twitter.com/proofpoint',
                        'youtube'       => 'https://www.youtube.com/channel/UCIvtJgsrUzFo90NKeiVozhQ',
                        'linkedin'      => 'https://www.linkedin.com/company/proofpoint',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Seqrite Blog',
                        'slug'          => 'seqrite-posts',
                        'url'           => 'https://blogs.seqrite.com/feed/',
                        'description'   => 'Seqrite Blog RSS Feed',
                        'website'       => 'https://blogs.seqrite.com/',
                        'facebook'      => 'https://www.facebook.com/seqrite',
                        'twitter'       => 'https://twitter.com/Seqrite',
                        'youtube'       => 'https://www.youtube.com/channel/UCPgS-p40ag_l8i3mhMWW7Gg',
                        'linkedin'      => 'https://www.linkedin.com/company/seqrite',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Data Sunrise',
                        'slug'          => 'data-sunrise',
                        'url'           => 'https://www.datasunrise.com/feed',
                        'description'   => 'Data Sunrise RSS Feed',
                        'website'       => 'https://www.datasunrise.com/posts/',
                        'facebook'      => 'https://www.facebook.com/datasunrise',
                        'twitter'       => 'https://twitter.com/datasunrise',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/datasunrise-inc',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'IT Security Central',
                        'slug'          => 'it-security-central',
                        'url'           => 'https://itsecuritycentral.teramind.co/feed',
                        'description'   => 'IT Security Central RSS Feed',
                        'website'       => 'https://itsecuritycentral.teramind.co/',
                        'facebook'      =>  'https://www.facebook.com/pages/Teramind/1523438361205247',
                        'twitter'       => 'https://twitter.com/teramindco',
                        'youtube'       => 'https://www.youtube.com/channel/UCSkRq9qTqFJyyjQdovb0-Lg',
                        'linkedin'      => 'https://www.linkedin.com/company/5090184',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Hacker Combat',
                        'slug'          => 'hacker-combat',
                        'url'           => 'https://hackercombat.com/feed',
                        'description'   => 'Hacker Combat | Cyber Security and Hacking News RSS Feed',
                        'website'       => 'https://www.hackercombat.com/',
                        'facebook'      => 'https://www.facebook.com/HackerCombatOfficial/',
                        'twitter'       => 'https://twitter.com/Hacker_Combat',
                        'youtube'       => 'https://www.youtube.com/channel/UC2RCg8h4Iz0_psgm75jpzNA',
                        'linkedin'      => 'https://www.linkedin.com/company/13592570',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    // Security weekly http://securityweekly.com/podcast/psw.xml | http://securityweekly.com/podcast/psw.xml
                    // [
                    //     'label'         => 'Connected',
                    //     'slug'          => 'connected-posts-community',
                    //     'url'           => 'https://community.connection.com/feed-connection/',
                    //     'description'   => 'Connected - Official Technology Community of Connection',
                    //     'website'       => 'https://community.connection.com/',
                    //     'facebook'      => '',
                    //     'twitter'       => '',
                    //     'youtube'       => '',
                    //     'linkedin'      => '',
                    //     'github'        => '',
                    //     'keywords'      => '',
                    //     'og_image'      => '',
                    // ],
                    [
                        'label'         => 'Cybersecurity 360',
                        'slug'          => 'cybersecurity-360',
                        'url'           => 'https://www.cybersecurity360.it/feed/',
                        'description'   => '',
                        'website'       => 'https://www.cybersecurity360.it/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Securelist.com',
                        'slug'          => 'securelist-com',
                        'url'           => 'https://securelist.com/feed/',
                        'description'   => 'Securelist - Kaspersky Lab\'s cyberthreat research and reports',
                        'website'       => '',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Darknet.org',
                        'slug'          => 'darknet-org',
                        'url'           => 'https://www.darknet.org.uk/feed/',
                        'description'   => "Darknet.org - Don't learn to hack, hack to learn!",
                        'website'       => 'https://www.darknet.org.uk/',
                        'facebook'      => 'https://www.facebook.com/profile.php?id=100086410801741',
                        'twitter'       => 'https://twitter.com/THEdarknet',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/25076296/',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    [
                        'label'         => 'Trend Micro',
                        'slug'          => 'trend-micro',
                        'url'           => 'http://feeds.trendmicro.com/TrendMicroSimplySecurity?format=xml',
                        'description'   => "Trend Micro Simply Security",
                        'website'       => '',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                    // [
                    //     'label'         => 'ISC2',
                    //     'slug'          => 'isc-2',
                    //     'url'           => '',
                    //     'description'   => 'ISC2 Trending Cybersecurity News',
                    //     'website'       => 'https://www.isc2.org/',
                    //     'facebook'      => '',
                    //     'twitter'       => '',
                    //     'youtube'       => '',
                    //     'linkedin'      => '',
                    //     'github'        => '',
                    //     'keywords'      => '',
                    //     'og_image'      => '',
                    // ],
                    [
                        'label'         => 'IT Governance Blog',
                        'slug'          => 'it-governance-blog',
                        'url'           => 'https://www.itgovernance.co.uk/blog/feed/',
                        'description'   => 'IT Governance Blog | Cyber Security RSS Feed',
                        'website'       => 'https://www.itgovernance.co.uk/blog/category/cyber-security/',
                        'facebook'      => 'https://www.facebook.com/ITGovernanceLtd',
                        'twitter'       => 'https://twitter.com/ITGovernance',
                        'youtube'       => 'http://www.youtube.com/itgovernanceltd',
                        'linkedin'      => 'https://www.linkedin.com/company/it-governance',
                        'github'        => '',
                        'keywords'      => '',
                        'og_image'      => '',
                    ],
                ]
            ],
            [
                'picture'       => 'fortinet.gif',
                'label'         => 'Fortinet',
                'description'   => 'Latest news from Fortinet',
                'slug'          => 'fortinet',
                'feeds' => [
                    [
                        'label'             => 'PSIRT Advisories',
                        'slug'              => 'psirt-advisories',
                        'url'               => 'https://fortiguard.com/rss/ir.xml',
                        'description'       => 'PSIRT Advisories',
                        'keywords'          => '',
                        'og_image'          => '',
                        'seo_title'         => '',
                        'seo_description'   => '',
                        'seo_keywords'      => ''
                    ],
                    [
                        'label'             => 'Application Control Service Updates',
                        'slug'              => 'application-control-service-updates',
                        'url'               => 'http://fortiguard.com/rss/appcontrol.xml',
                        'description'       => 'Application Control Service Updates',
                        'keywords'          => '',
                        'og_image'          => '',
                        'seo_title'         => '',
                        'seo_description'   => '',
                        'seo_keywords'      => ''
                    ],
                    [
                        'label'             => 'Antispam Checksum Updates',
                        'slug'              => 'antispam-checksum-updates',
                        'url'               => 'http://fortiguard.com/rss/aschecksum.xml',
                        'description'       => 'Application Control Service Updates',
                        'keywords'          => '',
                        'og_image'          => '',
                        'seo_title'         => '',
                        'seo_description'   => '',
                        'seo_keywords'      => ''
                    ],
                    [
                        'label'             => 'Antispam URI Updates',
                        'slug'              => 'antispam-uri-updates',
                        'url'               => 'http://fortiguard.com/rss/asuri.xml',
                        'description'       => 'Antispam URI Updates',
                        'keywords'          => '',
                        'og_image'          => '',
                        'seo_title'         => '',
                        'seo_description'   => '',
                        'seo_keywords'      => ''
                    ],
                    [
                        'label'             => 'Antispam IP Updates',
                        'slug'              => 'antispam-ip-updates',
                        'url'               => 'http://fortiguard.com/rss/asip.xml',
                        'description'       => 'Antispam URI Updates',
                        'keywords'          => '',
                        'og_image'          => '',
                        'seo_title'         => '',
                        'seo_description'   => '',
                        'seo_keywords'      => ''
                    ],
                    [
                        'label'             => 'Intrusion Prevention Service Updates',
                        'slug'              => 'intrusion-prevention-service-updates',
                        'url'               => 'http://fortiguard.com/rss/ipsdatabase.xml',
                        'description'       => 'Intrusion Prevention Service Updates',
                        'keywords'          => '',
                        'og_image'          => '',
                        'seo_title'         => '',
                        'seo_description'   => '',
                        'seo_keywords'      => ''
                    ],
                    [
                        'label'             => 'Web Filtering Service Updates',
                        'slug'              => 'web-filtering-service-updates',
                        'url'               => 'http://fortiguard.com/rss/webfiltering.xml',
                        'description'       => 'Web Filtering Service Updates',
                        'keywords'          => '',
                        'og_image'          => '',
                        'seo_title'         => '',
                        'seo_description'   => '',
                        'seo_keywords'      => ''
                    ],
                    [
                        'label'             => 'Web Filtering Service Updates',
                        'slug'              => 'web-filtering-service-updates',
                        'url'               => 'http://fortiguard.com/rss/webfiltering.xml',
                        'description'       => 'Web Filtering Service Updates',
                        'keywords'          => '',
                        'og_image'          => '',
                        'seo_title'         => '',
                        'seo_description'   => '',
                        'seo_keywords'      => ''
                    ],
                    [
                        'label'             => 'Web Security Service Updates',
                        'slug'              => 'web-security-service-updates',
                        'url'               => 'http://fortiguard.com/rss/websecurity.xml',
                        'description'       => 'Web Security Service Updates',
                        'keywords'          => '',
                        'og_image'          => '',
                        'seo_title'         => '',
                        'seo_description'   => '',
                        'seo_keywords'      => ''
                    ],
                    [
                        'label'             => 'Mobile AntiVirus Service Updates',
                        'slug'              => 'mobile-antiVirus-service-updates',
                        'url'               => 'http://fortiguard.com/rss/mobile.xml',
                        'description'       => 'Web Security Service Updates',
                        'keywords'          => '',
                        'og_image'          => '',
                        'seo_title'         => '',
                        'seo_description'   => '',
                        'seo_keywords'      => ''
                    ],
                    [
                        'label'             => 'Endpoint Vunerability Protection Updates',
                        'slug'              => 'endpoint-vunerability-protection-updates',
                        'url'               => 'http://fortiguard.com/rss/epvuln.xml',
                        'description'       => 'Web Security Service Updates',
                        'keywords'          => '',
                        'og_image'          => '',
                        'seo_title'         => '',
                        'seo_description'   => '',
                        'seo_keywords'      => ''
                    ],
                ]
            ],
        ];
    }
}
