<?php

namespace App\Models;

class CybersecurityFeeds implements FeedsListInterface
{
    public function getFeeds()
    {
        return [
            [
                'picture'       => 'threat-post.gif',
                'label'         => 'Threat Post',
                'description'   => 'Latest news from Threat Post',
                'slug'          => 'threat-post',
                'website'       => 'https://www.threatpost.com/',
                'youtube'       => 'https://www.youtube.com/user/threatpost',
                'facebook'      => 'https://www.facebook.com/Threatpost/',
                'twitter'       => 'https://twitter.com/threatpost/',
                'gplus'         => 'https://plus.google.com/103973344735603121561/posts',
                'linkedin'      => 'https://www.linkedin.com/groups/12103060',
                'feeds' => [
                    [
                        'label'         => 'Cloud Security',
                        'slug'          => 'threat-post-cloud-security',
                        'url'           => 'https://threatpost.com/category/cloud-security/feed',
                        'description'   => 'Cloud Security news on threat post',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Critical Infrastructure',
                        'slug'          => 'threat-post-critical-infrastructure',
                        'url'           => 'https://threatpost.com/category/critical-infrastructure/feed',
                        'description'   => 'Critical Infrastructure news on threat post',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Cryptography',
                        'slug'          => 'threat-post-cryptography',
                        'url'           => 'https://threatpost.com/category/critical-infrastructure/feed',
                        'description'   => 'Cryptography news on threat post',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Government',
                        'slug'          => 'threat-post-government',
                        'url'           => 'https://threatpost.com/category/government/feed',
                        'description'   => 'Government news on Threat Post',
                        'keywords'      => 'internet of thigs,threat post,'.'',
                    ],
                    [
                        'label'         => 'Hacks',
                        'slug'          => 'threat-post-hacks',
                        'url'           => 'https://threatpost.com/category/hacks/feed',
                        'description'   => 'Threat post Hackings news',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'IoT',
                        'slug'          => 'threat-post-iot',
                        'url'           => 'https://threatpost.com/category/iot/feed',
                        'description'   => 'Threat post Internet of Things news',
                        'keywords'      => 'internet of thigs,feed,threat post,hacking,security',
                    ],
                    [
                        'label'         => 'Mobile Security',
                        'slug'          => 'threat-post-mobile-security',
                        'url'           => 'https://threatpost.com/category/mobile-security/feed',
                        'description'   => 'Threat post Mobile Security news',
                        'keywords'      => 'mobile,security,feed,threat post,hacking,cyber,security',
                    ],
                    [
                        'label'         => 'Privacy',
                        'slug'          => 'threat-post-privacy',
                        'url'           => 'https://threatpost.com/category/privacy/feed',
                        'description'   => 'Threat post Privacy news',
                        'keywords'      => 'privacy,feed,threat post,hacking,cyber,security',
                    ],
                    [
                        'label'         => 'Vulnerabilities',
                        'slug'          => 'threat-post-vulnerabilities',
                        'url'           => 'https://threatpost.com/category/vulnerabilities/feed',
                        'description'   => 'Threat post Vulnerabilities news',
                        'keywords'      => 'vulnerabilities,feed,threat post,hacking,cyber,security',
                    ],
                    [
                        'label'         => 'Web Security',
                        'slug'          => 'threat-post-web-security',
                        'url'           => 'https://threatpost.com/category/web-security/feed',
                        'description'   => 'Threat post Vulnerabilities news',
                        'keywords'      => 'web security,feed,threat post,hacking,cyber,security',
                    ],
                    [
                        'label'         => 'Videos',
                        'slug'          => 'threat-post-videos',
                        'url'           => 'https://threatpost.com/category/videos/feed',
                        'description'   => 'Threat post Videos',
                        'keywords'      => '',
                    ],
                ]
            ],
            [
                'picture'               => 'cyber-security-websites.gif',
                'label'                 => 'Websites',
                'description'           => 'Information security news from the best websites and blogs',
                'slug'                  => 'websites',
                'feeds' => [
                    // Empty template
                    /*
                    [
                        'label'         => '',
                        'slug'          => '',
                        'url'           => '',
                        'description'   => '',
                        'website'       => '',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    */
                    [
                        'label'         => 'Graham Cluley - Cybersecurity and AI keynote speaker',
                        'slug'          => 'graham-cluley',
                        'url'           => 'https://grahamcluley.com/feed/',
                        'description'   => '',
                        'website'       => 'https://grahamcluley.com/writing/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => 'https://www.youtube.com/grahamcluleycom',
                        'linkedin'      => 'https://www.linkedin.com/in/grahamcluley/',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'ImmuniWeb - Cybercrime Investigations Weekly',
                        'slug'          => 'immuniweb',
                        'url'           => 'https://www.immuniweb.com/rssblog.rss',
                        'description'   => '',
                        'website'       => '',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Cisco Security',
                        'slug'          => 'cisco-security',
                        'url'           => 'https://blogs.cisco.com/security/feed',
                        'description'   => '',
                        'website'       => 'https://blogs.cisco.com/security',
                        'facebook'      => 'https://www.facebook.com/ciscosecurity',
                        'twitter'       => 'https://twitter.com/ciscosecure',
                        'youtube'       => 'https://www.youtube.com/user/Cisco/welcome',
                        'linkedin'      => 'https://www.linkedin.com/showcase/cisco-security',
                        'instagram'     => 'https://www.instagram.com/ciscosecurity',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Daniel Miessler',
                        'slug'          => 'daniel-miessler',
                        'url'           => 'https://danielmiessler.com/feed.rss',
                        'description'   => '',
                        'website'       => 'https://danielmiessler.com',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => 'https://www.youtube.com/@unsupervised-learning',
                        'linkedin'      => 'https://www.linkedin.com/in/danielmiessler/',
                        'github'        => 'https://github.com/danielmiessler',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Dark reading',
                        'slug'          => 'dark-reading',
                        'url'           => 'https://www.darkreading.com/rss.xml',
                        'description'   => 'Dark Reading is now the most trusted online community for security professionals',
                        'website'       => 'https://www.darkreading.com/',
                        'facebook'      => 'https://www.facebook.com/darkreadingcom/',
                        'twitter'       => '',
                        'youtube'       => 'https://www.youtube.com/@DarkReadingOfficialYT',
                        'linkedin'      => 'https://www.linkedin.com/company/dark-reading/',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'The Hacker News',
                        'slug'          => 'the-hacker-news',
                        'url'           => 'http://feeds.feedburner.com/TheHackersNews?format=xml',
                        'description'   => 'The Hacker News has been internationally recognized as a leading news source dedicated to promoting awareness for security experts and hackers',
                        'website'       => 'https://thehackernews.com/',
                        'facebook'      => 'https://www.facebook.com/thehackernews',
                        'twitter'       => 'https://twitter.com/thehackersnews',
                        'youtube'       => 'https://www.youtube.com/user/hackernewsvideos?sub_confirmation=1',
                        'linkedin'      => 'https://www.linkedin.com/company/the-hacker-news/',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'EC Council',
                        'slug'          => 'ec-council',
                        'url'           => 'https://www.eccouncil.org/feed/',
                        'description'   => 'EC-Council\'s New Learning Track Launched Globally',
                        'website'       => 'https://www.eccouncil.org/',
                        'facebook'      => 'https://www.facebook.com/ECCouncil',
                        'twitter'       => 'https://twitter.com/ECCOUNCIL',
                        'youtube'       => 'https://www.youtube.com/user/eccouncilusa',
                        'linkedin'      => 'https://www.linkedin.com/company/ec-council',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Kali Linux',
                        'slug'          => 'kali-linux',
                        'url'           => 'https://www.kali.org/feed/',
                        'description'   => 'Kali Linux RSS Feed',
                        'website'       => 'https://www.kali.org/',
                        'facebook'      => '',
                        'twitter'       => 'https://twitter.com/kalilinux',
                        'youtube'       => '',
                        'linkedin'      => 'http://www.linkedin.com/groups?gid=970937',
                        'github'        => 'https://github.com/offensive-security',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Krebs on Security',
                        'slug'          => 'krebs-on-security',
                        'url'           => 'https://krebsonsecurity.com/feed/',
                        'description'   => 'Krebs on Security RSS Feed',
                        'website'       => 'https://krebsonsecurity.com/',
                        'facebook'      => '',
                        'twitter'       => 'http://twitter.com/briankrebs',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/in/bkrebs/',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Schneier on Security',
                        'slug'          => 'krebs-on-security',
                        'url'           => 'https://www.schneier.com/tag/cybersecurity/feed/',
                        'description'   => '',
                        'website'       => 'https://www.schneier.com/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Naked Security',
                        'slug'          => 'naked-security',
                        'url'           => 'https://nakedsecurity.sophos.com/feed/',
                        'description'   => 'Naked Security RSS Feed',
                        'website'       => 'https://nakedsecurity.sophos.com/',
                        'facebook'      => 'https://www.facebook.com/SophosSecurity',
                        'twitter'       => 'https://twitter.com/#!/NakedSecurity',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/5053/',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Google Online Security Blog',
                        'slug'          => 'google-online-security-blog',
                        'url'           => 'http://feeds.feedburner.com/GoogleOnlineSecurityBlog',
                        'description'   => 'Google Online Security Blog RSS Feed',
                        'website'       => 'https://security.googleblog.com/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Security Affairs',
                        'slug'          => 'security-affairs',
                        'url'           => 'http://securityaffairs.co/wordpress/feed',
                        'description'   => 'Security Affairs RSS Feed',
                        'website'       => 'http://securityaffairs.co/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Security Week',
                        'slug'          => 'security-week',
                        'url'           => 'http://feeds.feedburner.com/Securityweek?format=xml',
                        'description'   => 'SecurityWeek | Information Security News, IT Security News & Expert Insights RSS Feed',
                        'website'       => 'http://www.securityweek.com/',
                        'facebook'      => 'https://www.facebook.com/SecurityWeekCom-366251913615/',
                        'twitter'       => 'https://twitter.com/securityweek',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/securityweek/',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Help Net Security',
                        'slug'          => 'help-net-security',
                        'url'           => 'https://www.helpnetsecurity.com/feed',
                        'description'   => 'Help Net Security RSS Feed',
                        'website'       => 'https://www.helpnetsecurity.com/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'HackRead',
                        'slug'          => 'hackread',
                        'url'           => 'https://www.hackread.com/feed',
                        'description'   => 'HackRead | Latest Cyber Crime - InfoSec - Tech - Hacking News RSS Feed',
                        'website'       => 'https://www.hackread.com/',
                        'facebook'      => 'https://facebook.com/HackRead',
                        'twitter'       => 'https://twitter.com/HackRead',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/10290450',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Search Security',
                        'slug'          => 'search-security',
                        'url'           => 'http://searchsecurity.techtarget.com/rss/Security-Wire-Daily-News.xml',
                        'description'   => 'SearchSecurity RSS Feed',
                        'website'       => 'https://searchsecurity.techtarget.com/',
                        'facebook'      => 'https://www.facebook.com/SearchSecurity.com/',
                        'twitter'       => 'https://x.com/techtargetnews',
                        'youtube'       => 'https://www.youtube.com/c/EyeonTech',
                        'linkedin'      => 'https://www.linkedin.com/showcase/techtarget-news/',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Security Gladiators',
                        'slug'          => 'security-gladiators',
                        'url'           => 'https://securitygladiators.com/internet-security-news/feed',
                        'description'   => 'Security Gladiators - Internet Security News RSS Feed',
                        'website'       => 'https://securitygladiators.com/internet-security-news/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'GBHackers On Security',
                        'slug'          => 'gbhackers-on-security',
                        'url'           => 'https://gbhackers.com/feed/',
                        'description'   => 'GBHackers On Security RSS Feed',
                        'website'       => 'https://www.gbhackers.com/',
                        'facebook'      => '',
                        'twitter'       => 'https://twitter.com/gbhackers_news',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/cybersecurity-news/',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Guardian computer security',
                        'slug'          => 'guardina-computer-security',
                        'url'           => 'https://www.theguardian.com/technology/data-computer-security/rss',
                        'description'   => '',
                        'website'       => 'https://www.theguardian.com/technology/data-computer-security',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Cisco Blog',
                        'slug'          => 'cisco-posts',
                        'url'           => 'http://blogs.cisco.com/category/security/feed/',
                        'description'   => 'Cisco Blog - Security RSS Feed',
                        'website'       => 'https://blogs.cisco.com/security',
                        'facebook'      => 'https://www.facebook.com/ciscosecurity',
                        'twitter'       => 'https://twitter.com/ciscosecurity',
                        'youtube'       => 'https://www.youtube.com/user/Cisco/',
                        'linkedin'      => 'http://www.linkedin.com/company/cisco',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    // TechRepublic https://www.techrepublic.com/topic/security/ | http://www.techrepublic.com/rssfeeds/topic/security/?feedType=rssfeeds
                    [
                        'label'         => 'Zero Day | ZDNet',
                        'slug'          => 'zero-day-zdnetw',
                        'url'           => 'https://www.zdnet.com/posts/security/rss.xml',
                        'description'   => 'Zero Day | ZDNet RSS Feed',
                        'website'       => 'https://www.zdnet.com',
                        'facebook'      => 'https://www.facebook.com/pages/ZDNet/5953112932',
                        'twitter'       => 'http://twitter.com/zdnet',
                        'youtube'       => 'https://www.youtube.com/channel/UCr9QWb5RKLfaunjKHJZAdQQ',
                        'linkedin'      => 'https://www.linkedin.com/company/zdnet-com',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'TRUSTe Blog',
                        'slug'          => 'truste-posts',
                        'url'           => 'http://www.trustarc.com/posts/feed/',
                        'description'   => 'TRUSTe Blog RSS Feed',
                        'website'       => 'https://www.trustarc.com/posts/',
                        'facebook'      => 'https://www.facebook.com/TrustArc/',
                        'twitter'       => 'https://twitter.com/trustarc',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/21121',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Threat Insight Blog',
                        'slug'          => 'threat-insight',
                        'url'           => 'https://www.proofpoint.com/us/rss.xml',
                        'description'   => 'Threat Insight Blog - Cybersecurity Intelligence | Proofpoint',
                        'website'       => 'https://www.proofpoint.com/',
                        'facebook'      => 'http://www.facebook.com/proofpoint',
                        'twitter'       => 'http://www.twitter.com/proofpoint',
                        'youtube'       => 'https://www.youtube.com/channel/UCIvtJgsrUzFo90NKeiVozhQ',
                        'linkedin'      => 'https://www.linkedin.com/company/proofpoint',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Seqrite Blog',
                        'slug'          => 'seqrite-posts',
                        'url'           => 'https://blogs.seqrite.com/feed/',
                        'description'   => 'Seqrite Blog RSS Feed',
                        'website'       => 'https://blogs.seqrite.com/',
                        'facebook'      => 'https://www.facebook.com/seqrite',
                        'twitter'       => 'https://twitter.com/Seqrite',
                        'youtube'       => 'https://www.youtube.com/channel/UCPgS-p40ag_l8i3mhMWW7Gg',
                        'linkedin'      => 'https://www.linkedin.com/company/seqrite',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    // [
                    //     'label'         => 'Data Sunrise',
                    //     'slug'          => 'data-sunrise',
                    //     'url'           => 'https://www.datasunrise.com/feed',
                    //     'description'   => 'Data Sunrise RSS Feed',
                    //     'website'       => 'https://www.datasunrise.com/posts/',
                    //     'facebook'      => 'https://www.facebook.com/datasunrise',
                    //     'twitter'       => 'https://twitter.com/datasunrise',
                    //     'youtube'       => '',
                    //     'linkedin'      => 'https://www.linkedin.com/company/datasunrise-inc',
                    //     'github'        => '',
                    //     'keywords'      => '',
                    // ],
                    [
                        'label'         => 'IT Security Central',
                        'slug'          => 'it-security-central',
                        'url'           => 'https://itsecuritycentral.teramind.co/feed',
                        'description'   => 'IT Security Central RSS Feed',
                        'website'       => 'https://itsecuritycentral.teramind.co/',
                        'facebook'      =>  'https://www.facebook.com/pages/Teramind/1523438361205247',
                        'twitter'       => 'https://twitter.com/teramindco',
                        'youtube'       => 'https://www.youtube.com/channel/UCSkRq9qTqFJyyjQdovb0-Lg',
                        'linkedin'      => 'https://www.linkedin.com/company/5090184',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Hacker Combat',
                        'slug'          => 'hacker-combat',
                        'url'           => 'https://hackercombat.com/feed',
                        'description'   => 'Hacker Combat | Cyber Security and Hacking News RSS Feed',
                        'website'       => 'https://www.hackercombat.com/',
                        'facebook'      => 'https://www.facebook.com/HackerCombatOfficial/',
                        'twitter'       => 'https://twitter.com/Hacker_Combat',
                        'youtube'       => 'https://www.youtube.com/channel/UC2RCg8h4Iz0_psgm75jpzNA',
                        'linkedin'      => 'https://www.linkedin.com/company/13592570',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    // Security weekly http://securityweekly.com/podcast/psw.xml | http://securityweekly.com/podcast/psw.xml
                    // [
                    //     'label'         => 'Connected',
                    //     'slug'          => 'connected-posts-community',
                    //     'url'           => 'https://community.connection.com/feed-connection/',
                    //     'description'   => 'Connected - Official Technology Community of Connection',
                    //     'website'       => 'https://community.connection.com/',
                    //     'facebook'      => '',
                    //     'twitter'       => '',
                    //     'youtube'       => '',
                    //     'linkedin'      => '',
                    //     'github'        => '',
                    //     'keywords'      => '',
                    // ],
                    [
                        'label'         => 'Cybersecurity 360',
                        'slug'          => 'cybersecurity-360',
                        'url'           => 'https://www.cybersecurity360.it/feed/',
                        'description'   => '',
                        'website'       => 'https://www.cybersecurity360.it/',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Securelist.com',
                        'slug'          => 'securelist-com',
                        'url'           => 'https://securelist.com/feed/',
                        'description'   => 'Securelist - Kaspersky Lab\'s cyberthreat research and reports',
                        'website'       => '',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Darknet.org',
                        'slug'          => 'darknet-org',
                        'url'           => 'https://www.darknet.org.uk/feed/',
                        'description'   => "Darknet.org - Don't learn to hack, hack to learn!",
                        'website'       => 'https://www.darknet.org.uk/',
                        'facebook'      => 'https://www.facebook.com/profile.php?id=100086410801741',
                        'twitter'       => 'https://twitter.com/THEdarknet',
                        'youtube'       => '',
                        'linkedin'      => 'https://www.linkedin.com/company/25076296/',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'Trend Micro',
                        'slug'          => 'trend-micro',
                        'url'           => 'http://feeds.trendmicro.com/TrendMicroSimplySecurity?format=xml',
                        'description'   => "Trend Micro Simply Security",
                        'website'       => '',
                        'facebook'      => '',
                        'twitter'       => '',
                        'youtube'       => '',
                        'linkedin'      => '',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                    [
                        'label'         => 'IT Governance Blog',
                        'slug'          => 'it-governance-blog',
                        'url'           => 'https://www.itgovernance.co.uk/blog/feed/',
                        'description'   => 'IT Governance Blog | Cyber Security RSS Feed',
                        'website'       => 'https://www.itgovernance.co.uk/blog/category/cyber-security/',
                        'facebook'      => 'https://www.facebook.com/ITGovernanceLtd',
                        'twitter'       => 'https://twitter.com/ITGovernance',
                        'youtube'       => 'http://www.youtube.com/itgovernanceltd',
                        'linkedin'      => 'https://www.linkedin.com/company/it-governance',
                        'github'        => '',
                        'keywords'      => '',
                    ],
                ]
            ],
            // [
            //     'picture'       => 'fortinet.gif',
            //     'label'         => 'Fortinet',
            //     'description'   => 'Latest news from Fortinet',
            //     'slug'          => 'fortinet',
            //     'feeds' => [
            //         [
            //             'label'             => 'PSIRT Advisories',
            //             'slug'              => 'psirt-advisories',
            //             'url'               => 'https://fortiguard.com/rss/ir.xml',
            //             'description'       => 'PSIRT Advisories',
            //             'keywords'          => '',
            //             'seo_title'         => '',
            //             'seo_description'   => '',
            //             'seo_keywords'      => ''
            //         ],
            //         [
            //             'label'             => 'Application Control Service Updates',
            //             'slug'              => 'application-control-service-updates',
            //             'url'               => 'http://fortiguard.com/rss/appcontrol.xml',
            //             'description'       => 'Application Control Service Updates',
            //             'keywords'          => '',
            //             'seo_title'         => '',
            //             'seo_description'   => '',
            //             'seo_keywords'      => '',
            //         ],
            //         [
            //             'label'             => 'Antispam Checksum Updates',
            //             'slug'              => 'antispam-checksum-updates',
            //             'url'               => 'http://fortiguard.com/rss/aschecksum.xml',
            //             'description'       => 'Application Control Service Updates',
            //             'keywords'          => '',
            //             'seo_title'         => '',
            //             'seo_description'   => '',
            //             'seo_keywords'      => '',
            //         ],
            //         [
            //             'label'             => 'Antispam URI Updates',
            //             'slug'              => 'antispam-uri-updates',
            //             'url'               => 'http://fortiguard.com/rss/asuri.xml',
            //             'description'       => 'Antispam URI Updates',
            //             'keywords'          => '',
            //             'seo_title'         => '',
            //             'seo_description'   => '',
            //             'seo_keywords'      => ''
            //         ],
            //         [
            //             'label'             => 'Intrusion Prevention Service Updates',
            //             'slug'              => 'intrusion-prevention-service-updates',
            //             'url'               => 'http://fortiguard.com/rss/ipsdatabase.xml',
            //             'description'       => 'Intrusion Prevention Service Updates',
            //             'keywords'          => '',
            //             'seo_title'         => '',
            //             'seo_description'   => '',
            //             'seo_keywords'      => ''
            //         ],
            //         [
            //             'label'             => 'Web Filtering Service Updates',
            //             'slug'              => 'web-filtering-service-updates',
            //             'url'               => 'http://fortiguard.com/rss/webfiltering.xml',
            //             'description'       => 'Web Filtering Service Updates',
            //             'keywords'          => '',
            //             'seo_title'         => '',
            //             'seo_description'   => '',
            //             'seo_keywords'      => ''
            //         ],
            //         [
            //             'label'             => 'Web Security Service Updates',
            //             'slug'              => 'web-security-service-updates',
            //             'url'               => 'http://fortiguard.com/rss/websecurity.xml',
            //             'description'       => 'Web Security Service Updates',
            //             'keywords'          => '',
            //             'seo_title'         => '',
            //             'seo_description'   => '',
            //             'seo_keywords'      => ''
            //         ],
            //         [
            //             'label'             => 'Mobile AntiVirus Service Updates',
            //             'slug'              => 'mobile-antiVirus-service-updates',
            //             'url'               => 'http://fortiguard.com/rss/mobile.xml',
            //             'description'       => 'Web Security Service Updates',
            //             'keywords'          => '',
            //             'seo_title'         => '',
            //             'seo_description'   => '',
            //             'seo_keywords'      => ''
            //         ],
            //         [
            //             'label'             => 'Endpoint Vunerability Protection Updates',
            //             'slug'              => 'endpoint-vunerability-protection-updates',
            //             'url'               => 'http://fortiguard.com/rss/epvuln.xml',
            //             'description'       => 'Web Security Service Updates',
            //             'keywords'          => '',
            //             'seo_title'         => '',
            //             'seo_description'   => '',
            //             'seo_keywords'      => ''
            //         ],
            //     ]
            // ],
        ];
    }
}
