<?php

namespace App\Models;

class NewsFeeds implements FeedsListInterface
{
    public function getFeeds()
    {
        return [
            [
                'label' => 'Websites',
                'slug' => 'websites',
                // 'nosorting' => true,
                'feeds' => [
                    //  [
                    //     'label'       => '',
                    //     'slug'        => '',
                    //     'url'         => '',
                    //     'description' => '',
                    //     'website'     => '',
                    //     'facebook'    => '',
                    //     'twitter'     => '',
                    //     'linkedin'    => '',
                    //     'youtube'     => '',
                    //     'github'      => '',
                    //     'keywords'    => '',
                    //     'og_image'    => '',
                    // ],
                    [
                        'label'       => 'New York times',
                        'slug'        => 'new-york-times',
                        'url'         => 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml',
                        'description' => '',
                        'website'     => 'https://www.nytimes.com/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                    [
                        'label'       => 'Il fatto Quotidiano (italian)',
                        'slug'        => 'il-fatto-quotidiano',
                        'url'         => 'https://www.ilfattoquotidiano.it/feed/',
                        'description' => '',
                        'website'     => 'https://www.ilfattoquotidiano.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                        'keywords'    => '',
                        'og_image'    => '',
                    ],
                ]
            ],
            [
                'label' => 'Ansa.it (italian)',
                'slug' => 'ansa',
                'nosorting' => true,
                'feeds' => [
                    //  [
                    //     'label'       => '',
                    //     'slug'        => '',
                    //     'url'         => '',
                    //     'description' => '',
                    //     'website'     => '',
                    //     'facebook'    => '',
                    //     'twitter'     => '',
                    //     'linkedin'    => '',
                    //     'youtube'     => '',
                    //     'github'      => '',
                    //     'keywords'    => '',
                    //     'og_image'    => '',
                    // ],
                    [
                        'label'       => 'Homepage',
                        'slug'        => 'ansa-homepage',
                        'url'         => 'http://www.ansa.it/sito/ansait_rss.xml',
                        'description' => '',
                        'website'     => 'http://www.ansa.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                    ],
                    [
                        'label'       => 'Cronaca',
                        'slug'        => 'ansa-cronaca',
                        'url'         => 'http://www.ansa.it/sito/notizie/cronaca/cronaca_rss.xml',
                        'description' => '',
                        'website'     => 'http://www.ansa.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                    ],
                    [
                        'label'       => 'Mondo',
                        'slug'        => 'ansa-mondo',
                        'url'         => 'http://www.ansa.it/sito/notizie/mondo/mondo_rss.xml',
                        'description' => '',
                        'website'     => 'http://www.ansa.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                    ],
                    [
                        'label'       => 'Economia',
                        'slug'        => 'ansa-economia',
                        'url'         => 'http://www.ansa.it/sito/notizie/economia/economia_rss.xml',
                        'description' => '',
                        'website'     => 'http://www.ansa.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                    ],
                    [
                        'label'       => 'Sport',
                        'slug'        => 'ansa-sport',
                        'url'         => 'http://www.ansa.it/sito/notizie/sport/sport_rss.xml',
                        'description' => '',
                        'website'     => 'http://www.ansa.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                    ],
                    // [
                    //     'label'       => 'Calcio',
                    //     'slug'        => 'ansa-calcio',
                    //     'url'         => 'http://www.ansa.it/sito/notizie/sport/calcio/calcio_rss.xml',
                    //     'description' => '',
                    //     'website'     => 'http://www.ansa.it/',
                    //     'facebook'    => '',
                    //     'twitter'     => '',
                    //     'linkedin'    => '',
                    //     'youtube'     => '',
                    //     'github'      => '',
                    // ],
                    [
                        'label'       => 'Cinema',
                        'slug'        => 'ansa-cinema',
                        'url'         => 'http://www.ansa.it/sito/notizie/cultura/cinema/cinema_rss.xml',
                        'description' => '',
                        'website'     => 'http://www.ansa.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                    ],
                    [
                        'label'       => 'Tecnologia',
                        'slug'        => 'ansa-tecnologia',
                        'url'         => 'http://www.ansa.it/sito/notizie/tecnologia/tecnologia_rss.xml',
                        'description' => '',
                        'website'     => 'http://www.ansa.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                    ],
                    [
                        'label'       => 'Ultima ora',
                        'slug'        => 'ansa-ultima-ora',
                        'url'         => 'http://www.ansa.it/sito/notizie/topnews/topnews_rss.xml',
                        'description' => '',
                        'website'     => 'http://www.ansa.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                    ],
                    [
                        'label'       => 'English news',
                        'slug'        => 'ansa-english-news',
                        'url'         => 'http://www.ansa.it/english/english_rss.xml',
                        'description' => '',
                        'website'     => 'http://www.ansa.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                    ],
                    [
                        'label'       => 'Foto',
                        'slug'        => 'ansa-foto',
                        'url'         => 'http://www.ansa.it/sito/photogallery/foto_rss.xml',
                        'description' => '',
                        'website'     => 'http://www.ansa.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                    ],
                    [
                        'label'       => 'Video',
                        'slug'        => 'ansa-video',
                        'url'         => 'http://www.ansa.it/sito/videogallery/video_rss.xml',
                        'description' => '',
                        'website'     => 'http://www.ansa.it/',
                        'facebook'    => '',
                        'twitter'     => '',
                        'linkedin'    => '',
                        'youtube'     => '',
                        'github'      => '',
                    ],
                ]
            ]
        ];
    }
}
