<?php

namespace App\Models;

class NewsFeeds implements FeedsListInterface
{
    public function getFeeds()
    {
        return [
            [
                'label' => 'CNN',
                'slug' => 'cnn',
                // 'country': 'U.S.A',
                // 'website': 'https://www.cnn.com',
                // 'youtube': 'https://www.youtube.com/user/CNN',
                // 'facebook': 'https://www.facebook.com/cnninternational',
                // 'twitter': 'https://twitter.com/cnni',
                // 'wikipedia': 'https://en.wikipedia.org/wiki/CNN',
                // 'rss': 'http://edition.cnn.com/services/rss/',
                'feeds' => [
                    [
                        'label' => 'Top stories',
                        'slug' => 'cnn-top-stories',
                        'url' => 'http://rss.cnn.com/rss/edition.rss',
                        'description' => '',
                    ],
                    [
                        'label' => 'World',
                        'slug' => 'cnn-world',
                        'url' => 'http://rss.cnn.com/rss/edition_world.rss',
                        'description' => '',
                    ],
                    [
                        'label' => 'Africa',
                        'slug' => 'cnn-africa',
                        'url' => 'http://rss.cnn.com/rss/edition_africa.rss',
                        'description' => '',
                    ],
                    [
                        'label' => 'Americas',
                        'slug' => 'cnn-americas',
                        'url' => 'http://rss.cnn.com/rss/edition_americas.rss',
                        'description' => '',
                    ],
                    [
                        'label' => 'Asias',
                        'slug' => 'cnn-asia',
                        'url' => 'http://rss.cnn.com/rss/edition_asia.rss',
                        'description' => '',
                    ],
                    [
                        'label' => 'U.S news',
                        'slug' => 'cnn-us',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/edition_us.rss'
                    ],
                    [
                        'label' => 'Money',
                        'slug' => 'cnn-money',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/money_news_international.rss'
                    ],
                    [
                        'label' => 'Technology',
                        'slug' => 'cnn-technology',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/edition_technology.rss'
                    ],
                    [
                        'label' => 'Science and space',
                        'slug' => 'cnn-science-space',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/edition_space.rss'
                    ],
                    [
                        'label' => 'Entertainment',
                        'slug' => 'cnn-entertainment',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/edition_entertainment.rss'
                    ],
                    [
                        'slug' => 'cnn-world-sport',
                        'label' => 'World Sport news',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/edition_sport.rss'
                    ],
                    [
                        'slug' => 'Football',
                        'label' => 'Football',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/edition_football.rss'
                    ],
                    [
                        'label' => 'Golf',
                        'slug' => 'cnn-golf',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/edition_golf.rss'
                    ],
                    [
                        'label' => 'Motorsport',
                        'slug' => 'cnn-motorsport',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/edition_motorsport.rss'
                    ],
                    [
                        'label' => 'Tennis',
                        'slug' => 'cnn-tennis',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/edition_tennis.rss'
                    ],
                    [
                        'label' => 'Travel',
                        'slug' => 'cnn-travel',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/edition_travel.rss'
                    ],
                    [
                        'label' => 'Travel',
                        'slug' => 'cnn-video',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/cnn_freevideo.rss'
                    ],
                    [
                        'label' => 'Most recent news',
                        'slug' => 'cnn-most-recent',
                        'description' => '',
                        'url' => 'http://rss.cnn.com/rss/cnn_latest.rss'
                    ],
                ],
            ],
            [
                'label' => 'Ansa.it (italian)',
                'slug' => 'ansa',
                'nosorting' => true,
                'feeds' => [
                    //  [
                    //     'label'       => '',
                    //     'slug'        => '',
                    //     'url'         => '',
                    //     'description' => '',
                    //     'website'     => '',
                    //     'facebook'    => '',
                    //     'twitter'     => '',
                    //     'linkedin'    => '',
                    //     'youtube'     => '',
                    //     'github'      => '',
                    //     'keywords'    => '',
                    //     'og_image'    => '',
                    // ],
                    [
                        'label' => 'Homepage',
                        'slug' => 'ansa-homepage',
                        'url' => 'http://www.ansa.it/sito/ansait_rss.xml',
                        'description' => '',
                        'website' => 'http://www.ansa.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                    ],
                    [
                        'label' => 'Cronaca',
                        'slug' => 'ansa-cronaca',
                        'url' => 'http://www.ansa.it/sito/notizie/cronaca/cronaca_rss.xml',
                        'description' => '',
                        'website' => 'http://www.ansa.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                    ],
                    [
                        'label' => 'Mondo',
                        'slug' => 'ansa-mondo',
                        'url' => 'http://www.ansa.it/sito/notizie/mondo/mondo_rss.xml',
                        'description' => '',
                        'website' => 'http://www.ansa.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                    ],
                    [
                        'label' => 'Economia',
                        'slug' => 'ansa-economia',
                        'url' => 'http://www.ansa.it/sito/notizie/economia/economia_rss.xml',
                        'description' => '',
                        'website' => 'http://www.ansa.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                    ],
                    [
                        'label' => 'Sport',
                        'slug' => 'ansa-sport',
                        'url' => 'http://www.ansa.it/sito/notizie/sport/sport_rss.xml',
                        'description' => '',
                        'website' => 'http://www.ansa.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                    ],
                    [
                        'label' => 'Cinema',
                        'slug' => 'ansa-cinema',
                        'url' => 'http://www.ansa.it/sito/notizie/cultura/cinema/cinema_rss.xml',
                        'description' => '',
                        'website' => 'http://www.ansa.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                    ],
                    [
                        'label' => 'Tecnologia',
                        'slug' => 'ansa-tecnologia',
                        'url' => 'http://www.ansa.it/sito/notizie/tecnologia/tecnologia_rss.xml',
                        'description' => '',
                        'website' => 'http://www.ansa.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                    ],
                    [
                        'label' => 'Ultima ora',
                        'slug' => 'ansa-ultima-ora',
                        'url' => 'http://www.ansa.it/sito/notizie/topnews/topnews_rss.xml',
                        'description' => '',
                        'website' => 'http://www.ansa.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                    ],
                    [
                        'label' => 'English news',
                        'slug' => 'ansa-english-news',
                        'url' => 'http://www.ansa.it/english/english_rss.xml',
                        'description' => '',
                        'website' => 'http://www.ansa.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                    ],
                    [
                        'label' => 'Foto',
                        'slug' => 'ansa-foto',
                        'url' => 'http://www.ansa.it/sito/photogallery/foto_rss.xml',
                        'description' => '',
                        'website' => 'http://www.ansa.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                    ],
                    [
                        'label' => 'Video',
                        'slug' => 'ansa-video',
                        'url' => 'http://www.ansa.it/sito/videogallery/video_rss.xml',
                        'description' => '',
                        'website' => 'http://www.ansa.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                    ],
                ]
            ],
            [
                'label' => 'Websites',
                'slug' => 'websites',
                // 'nosorting' => true,
                'feeds' => [
                    //  [
                    //     'label'       => '',
                    //     'slug'        => '',
                    //     'url'         => '',
                    //     'description' => '',
                    //     'website'     => '',
                    //     'facebook'    => '',
                    //     'twitter'     => '',
                    //     'linkedin'    => '',
                    //     'youtube'     => '',
                    //     'github'      => '',
                    //     'keywords'    => '',
                    //     'og_image'    => '',
                    // ],
                    [
                        'label' => 'New York times',
                        'slug' => 'new-york-times',
                        'url' => 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml',
                        'description' => '',
                        'website' => 'https://www.nytimes.com/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                        'og_image' => '',
                    ],
                    [
                        'label' => 'Il fatto Quotidiano (italian)',
                        'slug' => 'il-fatto-quotidiano',
                        'url' => 'https://www.ilfattoquotidiano.it/feed/',
                        'description' => '',
                        'website' => 'https://www.ilfattoquotidiano.it/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                        'og_image' => '',
                    ],
                ]
            ],
        ];
    }
}
