<?php

namespace App\Models;

class SoftwareDevelopmentFeeds implements FeedsListInterface
{
    public function getFeeds(): array
    {
        return [
            [
                'label' => 'PHP',
                'slug' => 'php',
                'nosorting' => true,
                'feeds' => [
                    // [
                    //     'label'         => '',
                    //     'slug'          => '',
                    //     'url'           => '',
                    //     'description'   => '',
                    //     'website'       => '',
                    //     'facebook'      => '',
                    //     'twitter'       => '',
                    //     'linkedin'      => '',
                    //     'youtube'       => '',
                    //     'github'        => '',
                    //     'keywords'      => '',
                    // ],
                    [
                        'label' => 'PHP.net official website',
                        'slug' => 'php-net',
                        'url' => 'https://www.php.net/feed.atom',
                        'description' => 'PHP official website latest news',
                        'website' => 'https://www.php.net/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/official_php',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'PHP.net releases',
                        'slug' => 'php-net-releases',
                        'url' => 'https://www.php.net/releases/feed.php',
                        'description' => 'PHP official website latest release',
                        'website' => 'https://www.php.net/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/official_php',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Laravel blog',
                        'slug' => 'laravel-blog',
                        'url' => 'https://blog.laravel.com/feed',
                        'description' => '',
                        'website' => 'https://blog.laravel.com/',
                        'facebook' => '',
                        'twitter' => 'https://x.com/laravelphp',
                        'linkedin' => '',
                        'youtube' => 'https://www.youtube.com/@LaravelPHP',
                        'github' => 'https://github.com/laravel/laravel',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Laracasts',
                        'slug' => 'laracasts',
                        'url' => 'https://laracasts.com/feed',
                        'description' => 'Latest posts from Laracasts',
                        'website' => 'https://laracasts.com/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/laracasts',
                        'linkedin' => '',
                        'youtube' => 'https://www.youtube.com/laracastsofficial',
                        'github' => 'https://github.com/laracasts',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Larajobs',
                        'slug' => 'larajobs',
                        'url' => 'https://larajobs.com/feed',
                        'description' => '',
                        'website' => 'https://larajobs.com/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Symfony',
                        'slug' => 'symfony',
                        'url' => 'https://feeds.feedburner.com/symfony/blog',
                        'description' => 'Symfony framework and components latest posts posts',
                        'website' => 'https://symfony.com/',
                        'facebook' => 'https://www.facebook.com/SymfonyFramework',
                        'twitter' => 'https://twitter.com/symfony',
                        'linkedin' => '',
                        'youtube' => 'https://www.youtube.com/user/SensioLabs',
                        'github' => 'https://github.com/symfony/symfony',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Yii framework',
                        'slug' => 'yii-framework',
                        'url' => 'https://www.yiiframework.com/rss.xml',
                        'description' => 'Yii 2 framework latest news',
                        'website' => 'https://www.yiiframework.com/',
                        'facebook' => 'https://www.facebook.com/groups/yiitalk/',
                        'twitter' => 'https://twitter.com/yiiframework',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => 'https://github.com/yiisoft',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Laminas blog',
                        'slug' => 'zend-posts',
                        'url' => 'https://getlaminas.org/blog/rss.xml',
                        'description' => 'Zend framework feeds from the posts',
                        'website' => 'https://framework.zend.com/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/zfdevteam',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => 'https://github.com/laminas',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'PHP classes .org',
                        'slug' => 'php-classes',
                        'url' => 'https://feedly.com/new-features/feed.xml',
                        'description' => '',
                        'website' => 'https://www.phpclasses.org/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    // https://laraveldaily.com/ GOOD WEBSITE BUT NO FEEDS
                    [
                        'label' => 'PHP Round table',
                        'slug' => 'php-round-table',
                        'url' => 'https://feeds.simplecast.com/sREPxPje',
                        'description' => 'PHP Round table: news from the Test fest event',
                        'website' => 'https://www.phproundtable.com/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/PHPRoundtable',
                        'linkedin' => '',
                        'youtube' => 'https://youtube.com/c/PHPRoundtable',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Ash Allen',
                        'slug' => 'ash-alllen-blog',
                        'url' => 'https://ashallendesign.co.uk/rss/blog',
                        'description' => 'Ash Allen design blog',
                        'website' => 'https://ashallendesign.co.uk/',
                        'facebook' => 'https://www.facebook.com/ashallendesignuk/',
                        'twitter' => '',
                        'linkedin' => 'https://linkedin.com/company/ash-allen-design',
                        'youtube' => '',
                        'github' => 'https://github.com/ash-jc-allen',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'David Carr',
                        'slug' => 'david-carr-laravel-developer',
                        'url' => 'https://dcblog.dev/feed',
                        'description' => 'David Carr, Laravel developer (TALL stack)',
                        'website' => 'https://dcblog.dev/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/dcblogdev',
                        'linkedin' => '',
                        'youtube' => 'https://www.youtube.com/c/dcblogdev',
                        'github' => 'https://github.com/dcblogdev',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Rob Allen',
                        'slug' => 'rob-allen',
                        'url' => 'https://akrabat.com/feed/',
                        'description' => 'Rob Allen\'s latest posts',
                        'website' => 'https://akrabat.com/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Jordi Boggiano',
                        'slug' => 'jordi-boggiano',
                        'url' => 'https://seld.be/feed.atom',
                        'description' => 'Lead developer on Composer. Symfony2 developer. Partner at Nelmio.',
                        'website' => 'https://seld.be/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/seldaek',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Dries Buytaert',
                        'slug' => 'dries-buytaert',
                        'url' => 'https://dri.es/rss.xml',
                        'description' => 'Open Source advocate, startup founder, technology executive, academic, hobbyist photographer, and father of two wonderful kids.',
                        'website' => 'https://dri.es/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Angie Byron',
                        'slug' => 'angie-byron',
                        'url' => 'http://www.webchick.net/rss.xml',
                        'description' => 'Senior Director of Product Management and Community Development at Acquia. Current Drupal core co-maintainer and past Drupal Association board member; also Development Manager for Drupal Spark, a Drupal distribution focused on user experience enhancements. Co-author of Using Drupal, 3rd Edition (2016).',
                        'website' => 'http://www.webchick.net/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/webchick',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    //                    Other PHP devs https://blog.newrelic.com/culture/php-developers-follow-online/
//                    [
//                        'label'         => '',
//                        'slug'          => '',
//                        'url'           => '',
//                        'description'   => '',
//                        'website'       => '',
//                        'facebook'      => '',
//                        'twitter'       => '',
//                        'linkedin'      => '',
//                        'youtube'       => '',
//                        'github'        => '',
//                        'keywords'      => '',
//                    ],
                ],
            ],
            [
                'label' => 'Python',
                'slug' => 'python',
                'feeds' => [
                    [
                        'label' => 'Planet Python',
                        'slug' => 'planet-python',
                        'url' => 'http://planetpython.org/rss20.xml',
                        'description' => '',
                        'website' => 'http://planetpython.org/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Practical Business Python',
                        'slug' => 'practical-business-python',
                        'url' => 'https://pbpython.com/feeds/all.atom.xml',
                        'description' => 'Taking care of business, one python script at a time',
                        'website' => 'https://pbpython.com/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Stack Abuse',
                        'slug' => 'stack-abuse',
                        'url' => 'https://stackabuse.com/rss/',
                        'description' => 'NodeJS,Java,Python and job news',
                        'website' => '',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Real Python',
                        'slug' => 'real-python',
                        'url' => 'https://realpython.com/atom.xml?format=xml',
                        'description' => '',
                        'website' => 'https://realpython.com/posts/',
                        'facebook' => 'https://facebook.com/LearnRealPython',
                        'twitter' => 'https://twitter.com/realpython',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Python Tips',
                        'slug' => 'python-tips',
                        'url' => 'https://pythontips.com/feed',
                        'description' => 'Your daily dose of bite sized python tips',
                        'website' => 'https://pythontips.com/',
                        'facebook' => 'https://www.facebook.com/freepythontips/',
                        'twitter' => 'https://twitter.com/yasoobkhalid/',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => 'https://github.com/yasoob/',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Pycoders',
                        'slug' => 'pycoders',
                        'url' => 'https://pycoders.com/feed/sDJprg8w',
                        'description' => 'PyCoder\'s Weekly news',
                        'website' => 'https://pycoders.com/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/pycoders',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Django Framework',
                        'slug' => 'django-framework',
                        'url' => 'https://www.djangoproject.com/rss/weblog/',
                        'description' => 'Django Framework latest news',
                        'website' => 'https://www.djangoproject.com/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/djangoproject',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => 'https://github.com/django',
                        'keywords' => '',
                    ],
                ],
            ],
            [
                'label' => 'Java',
                'slug' => 'java',
                'feeds' => [
                    // [
                    //     'label'         => 'Java World',
                    //     'slug'          => 'java-world',
                    //     'url'           => 'http://www.javaworld.com/index.rss',
                    //     'description'   => 'The original independent resource for Java developers, architects, and managers.',
                    //     'website'       => '',
                    //     'facebook'      => '',
                    //     'twitter'       => '',
                    //     'linkedin'      => '',
                    //     'youtube'       => '',
                    //     'github'        => '',
                    //     'keywords'      => '',
                    // ],
                    [
                        'label' => 'Java Code Geeks',
                        'slug' => 'java-code-geeks',
                        'url' => 'https://www.javacodegeeks.com/feed',
                        'description' => 'Java Code Geeks is an independent online community focused on creating the ultimate Java-to-Java developers resource center; targeted at the technical architect, technical team lead (senior developer), project manager and junior developers alike. JCGs serve the Java, Scala, Android, SOA, Agile and Telecom communities with daily news written by domain experts.',
                        'website' => '',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Oracle Blogs',
                        'slug' => 'oracle-blogs',
                        'url' => 'https://blogs.oracle.com/java/rss',
                        'description' => 'Java Code Geeks is an independent online community focused on creating the ultimate Java-to-Java developers resource center; targeted at the technical architect, technical team lead (senior developer), project manager and junior developers alike. JCGs serve the Java, Scala, Android, SOA, Agile and Telecom communities with daily news written by domain experts.',
                        'website' => '',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Java Revisited',
                        'slug' => 'java-revisited',
                        'url' => 'http://javarevisited.blogspot.com/feeds/posts/default',
                        'description' => 'To become goto place for Java Programmers, Interview question, SQL developer and anyone who wants to become better software programmer. Authored by Javin Paul.',
                        'website' => 'http://javarevisited.blogspot.com/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Thoughts on Java',
                        'slug' => 'thoughts-on-java',
                        'url' => 'http://www.thoughts-on-java.org/feed',
                        'description' => '',
                        'website' => 'http://www.thoughts-on-java.org/posts/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Baeldung',
                        'slug' => 'baeldung',
                        'url' => 'https://feeds.feedblitz.com/baeldung&x=1',
                        'description' => '',
                        'website' => 'https://www.baeldung.com/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],

                    // TODO add stackAbuse,
                ],
            ],
            [
                'label' => 'Sofware Engineers',
                'slug' => 'sofware-engineers',
                'feeds' => [
                    [
                        'label' => 'Martin Fowler',
                        'slug' => 'martin-fowler',
                        'url' => 'https://martinfowler.com/feed.atom',
                        'description' => 'Martin Fowler website, latest news',
                        'website' => 'https://martinfowler.com',
                        'facebook' => '',
                        'twitter' => 'https://www.twitter.com/martinfowler',
                        'linkedin' => 'https://www.linkedin.com/in/martin-fowler-com/',
                        'keywords' => '',
                    ],
                    // [
                    //     'label' => 'Scott Berkun',
                    //     'slug' => 'scott-berkun',
                    //     'url' => 'https://scottberkun.com/feed/',
                    //     'description' => '',
                    //     'website' => 'https://scottberkun.com/',
                    //     'facebook' => '',
                    //     'twitter' => '',
                    //     'linkedin' => '',
                    //     'youtube' => '',
                    //     'github' => '',
                    //     'keywords' => '',
                    // ],
                    [
                        'label' => 'Software Engineering Daily',
                        'slug' => 'software-engineering-daily',
                        'url' => 'https://softwareengineeringdaily.com/feed/',
                        'description' => '',
                        'website' => 'https://softwareengineeringdaily.com/',
                        'facebook' => 'https://www.facebook.com/sedaily',
                        'twitter' => 'https://twitter.com/software_daily',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'AirBnb on Medium',
                        'slug' => 'airbnb-on-medium',
                        'url' => 'https://medium.com/feed/airbnb-engineering',
                        'description' => '',
                        'website' => 'https://medium.com/airbnb-engineering',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Meta Engineering',
                        'slug' => 'meta-engineering',
                        'url' => 'https://engineering.fb.com/feed/',
                        'description' => '',
                        'website' => 'https://medium.com/airbnb-engineering',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Google developers experts',
                        'slug' => 'google-developers-experts',
                        'url' => 'https://medium.com/feed/google-developer-experts',
                        'description' => 'https://medium.com/google-developer-experts',
                        'website' => '',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Stackoverflow',
                        'slug' => 'stackoverflow',
                        'url' => 'https://stackoverflow.blog/feed/',
                        'description' => '',
                        'website' => 'https://stackoverflow.blog/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/stackoverflow/',
                        'linkedin' => 'https://linkedin.com/company/stack-overflow/',
                        'youtube' => '',
                        'instagram' => 'https://www.instagram.com/thestackoverflow/',
                        'github' => '',
                        'keywords' => '',
                    ],
                ],
            ],
            [
                'label' => 'Frontend Development',
                'slug' => 'frontend-development',
                'feeds' => [
                    [
                        'label' => 'Smashing Magazine',
                        'slug' => 'smashing-magazine',
                        'url' => 'https://www.smashingmagazine.com/feed',
                        'description' => 'Smashing Magazine - For Professional Web Designers and Developers',
                        'website' => 'https://www.smashingmagazine.com/',
                        'facebook' => '',
                        'twitter' => 'https://twitter.com/smashingmag',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Sitepoint',
                        'slug' => 'sitepoint',
                        'url' => 'https://www.sitepoint.com/feed/',
                        'description' => 'Latest posts from Sitepoint',
                        'website' => 'https://www.sitepoint.com/',
                        'facebook' => 'https://www.facebook.com/sitepoint',
                        'twitter' => 'https://twitter.com/sitepointdotcom',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Codrops',
                        'slug' => 'codrops',
                        'url' => 'http://tympanus.net/codrops/feed/',
                        'description' => 'Codrops | Useful resources and inspiration for creative minds',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'A list apart',
                        'slug' => 'a-list-apart',
                        'url' => 'https://alistapart.com/main/feed',
                        'description' => 'A List Apart: For People Who Make Websites',
                        'website' => '',
                        'facebook' => 'https://www.facebook.com/alistapart',
                        'twitter' => 'https://www.twitter.com/alistapart',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Webdesigner Depot',
                        'slug' => 'webdesigner-depot',
                        'url' => 'http://www.webdesignerdepot.com/feed/',
                        'description' => 'Webdesigner Depot - Web Design Blog',
                        'website' => 'http://www.webdesignerdepot.com',
                        'facebook' => 'https://www.facebook.com/webdesignerdepot',
                        'twitter' => 'https://twitter.com/designerdepot',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Toptal',
                        'slug' => 'toptal',
                        'url' => 'https://www.toptal.com/posts.rss',
                        'description' => 'Latest articles on Toptal.',
                        'website' => 'https://www.toptal.com/',
                        'facebook' => 'https://www.facebook.com/toptal',
                        'twitter' => 'https://twitter.com/toptal',
                        'linkedin' => 'https://www.linkedin.com/company/toptal',
                        'instagram' => 'https://www.instagram.com/toptal/',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Flavio Copes',
                        'slug' => 'flavio-copes',
                        'url' => 'https://flaviocopes.com/rss.xml',
                        'description' => 'I help people learn to code.',
                        'website' => 'https://flaviocopes.com/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Dev.to',
                        'slug' => 'devto',
                        'url' => 'https://dev.to/feed',
                        'description' => '',
                        'website' => 'https://dev.to/',
                        'facebook' => 'https://facebook.com/thepracticaldev',
                        'twitter' => 'https://x.com/thepracticaldev',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => 'https://github.com/forem',
                        'instagram' => 'https://instagram.com/thepracticaldev',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'CSS Tricks',
                        'slug' => 'css-tricks',
                        'url' => 'https://css-tricks.com/feed',
                        'description' => 'Latest articles on Tutsplus',
                        'website' => 'https://css-tricks.com/',
                        'facebook' => 'https://www.facebook.com/CSSTricks',
                        'twitter' => 'https://twitter.com/CSS',
                        'linkedin' => '',
                        'youtube' => 'https://www.youtube.com/user/realcsstricks',
                        'github' => '',
                        'keywords' => '',
                    ],
                    [
                        'label' => 'Angular blog Official',
                        'slug' => 'angular',
                        'url' => 'https://blog.angular.dev/feed',
                        'description' => '',
                        'website' => 'https://angular.io/',
                        'facebook' => '',
                        'twitter' => '',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                    // [
                    //     'label' => 'Angular in Depth',
                    //     'slug' => 'angular-in-depth',
                    //     'url' => 'https://posts.angularindepth.com/feed',
                    //     'description' => 'Latest articles on Angular in Depth',
                    //     'website' => '',
                    //     'facebook' => '',
                    //     'twitter' => '',
                    //     'linkedin' => '',
                    //     'youtube' => '',
                    //     'github' => '',
                    //     'keywords' => '',
                    // ],
                    [
                        'label' => 'ReactJS',
                        'slug' => 'react-js',
                        'url' => 'https://reactjs.org/feed.xml',
                        'description' => 'Latest articles about ReactJS',
                        'website' => 'https://reactjs.org/',
                        'facebook' => 'https://www.facebook.com/react',
                        'twitter' => 'https://twitter.com/reactjs',
                        'linkedin' => '',
                        'youtube' => '',
                        'github' => '',
                        'keywords' => '',
                    ],
                ],
            ],
            [
                'label' => 'Dzone',
                'slug' => 'dzone',
                'website' => 'https://dzone.com/',
                'facebook' => 'https://www.facebook.com/DZoneInc',
                'twitter' => 'https://twitter.com/DZoneInc',
                'linkedin' => 'https://www.linkedin.com/company/dzone/',
                'youtube' => '',
                'github' => '',
                'keywords' => '',
                'feeds' => [
                    [
                        'label' => 'Dzone Home',
                        'slug' => 'home',
                        'url' => 'https://feeds.dzone.com/home',
                        'description' => '',
                    ],
                    [
                        'label' => 'All contents',
                        'description' => 'All DZone content in one place',
                        'slug' => 'all-contents',
                        'url' => 'https://feeds.dzone.com/home'
                    ],
                    [
                        'label' => 'AI\ML Zone',
                        'description' => 'Latest articles from AI Zone',
                        'slug' => 'ai-ml-zone',
                        'url' => 'https://feeds.dzone.com/ai'
                    ],
                    [
                        'label' => 'Agile Zone',
                        'description' => 'Latest articles from Agile Zone',
                        'slug' => 'agile-zone',
                        'url' => 'https://feeds.dzone.com/agile'
                    ],
                    [
                        'label' => 'Big Data Zone',
                        'description' => 'Latest articles from Big Data Zone',
                        'slug' => 'big-data-zone',
                        'url' => 'http://feeds.dzone.com/big-data'
                    ],
                    [
                        'label' => 'Career Development Zone ',
                        'description' => '',
                        'slug' => 'career-development-zone',
                        'url' => 'https://feeds.dzone.com/career-development'
                    ],
                    [
                        'label' => 'Cloud Architecture Zone',
                        'description' => '',
                        'slug' => 'cloud-architecture-zone',
                        'url' => 'https://feeds.dzone.com/cloud-architecture'
                    ],
                    [
                        'label' => 'Containers',
                        'description' => '',
                        'slug' => 'containers',
                        'url' => 'https://feeds.dzone.com/containers'
                    ],
                    [
                        'label' => 'Data Zone',
                        'description' => '',
                        'slug' => 'data-zone',
                        'url' => 'https://feeds.dzone.com/data'
                    ],
                    [
                        'label' => 'Database Zone',
                        'description' => '',
                        'slug' => 'database-zone',
                        'url' => 'https://feeds.dzone.com/databases'
                    ],
                    [
                        'label' => 'Deployment Zone',
                        'description' => '',
                        'slug' => 'deployment-zone',
                        'url' => 'https://feeds.dzone.com/deployment'
                    ],
                    [
                        'label' => 'DevOps and CI/CD',
                        'description' => '',
                        'slug' => 'devops',
                        'url' => 'https://feeds.dzone.com/devops-and-cicd'
                    ],
                    [
                        'label' => 'Frameworks',
                        'description' => '',
                        'slug' => 'frameworks',
                        'url' => 'https://feeds.dzone.com/frameworks'
                    ],
                    [
                        'label' => 'Integration',
                        'description' => 'Latest articles from Integration Zone',
                        'slug' => 'integration',
                        'url' => 'https://feeds.dzone.com/integration'
                    ],
                    [
                        'label' => 'IoT',
                        'description' => 'Latest articles from IoT Zone',
                        'slug' => 'iot',
                        'url' => 'https://feeds.dzone.com/iot'
                    ],
                    [
                        'label' => 'Java',
                        'description' => 'Latest articles from Java Zone',
                        'slug' => 'java',
                        'url' => 'http://feeds.dzone.com/java'
                    ],
                    [
                        'label' => 'Javascript',
                        'description' => 'Latest articles from Javascript Zone',
                        'slug' => 'javascript',
                        'url' => 'http://feeds.dzone.com/javascript'
                    ],
                    [
                        'label' => 'Languages',
                        'description' => '',
                        'slug' => 'languages-zone',
                        'url' => 'https://feeds.dzone.com/languages'
                    ],
                    [
                        'label' => 'Maintenance ',
                        'description' => '',
                        'slug' => 'maintenance -zone',
                        'url' => 'https://feeds.dzone.com/maintenance'
                    ],
                    [
                        'label' => 'Methodologies',
                        'description' => '',
                        'slug' => 'methodologies',
                        'url' => 'https://feeds.dzone.com/methodologies'
                    ],
                    [
                        'label' => 'Microservices',
                        'description' => '',
                        'slug' => 'microservices',
                        'url' => 'https://feeds.dzone.com/microservices'
                    ],
                    [
                        'label' => 'Monitoring and Observability',
                        'description' => '',
                        'slug' => 'monitoring-and-observability',
                        'url' => 'https://feeds.dzone.com/monitoring-and-observability'
                    ],
                    [
                        'label' => 'Open Source',
                        'description' => '',
                        'slug' => 'open-source',
                        'url' => 'https://feeds.dzone.com/open-source'
                    ],
                    [
                        'label' => 'Performance',
                        'description' => 'Latest articles from Performance Zone',
                        'slug' => 'performance',
                        'url' => 'https://feeds.dzone.com/performance'
                    ],
                    [
                        'label' => 'Publications',
                        'description' => 'Latest DZone Research Guides and Refcardz',
                        'slug' => 'publications',
                        'url' => 'https://feeds.dzone.com/publications'
                    ],
                    [
                        'label' => 'Security zone',
                        'description' => 'Latest articles from Security Zone',
                        'slug' => 'security',
                        'url' => 'https://feeds.dzone.com/security'
                    ],
                    [
                        'label' => 'Team management',
                        'description' => '',
                        'slug' => 'team-management',
                        'url' => 'https://feeds.dzone.com/team-management'
                    ],
                    [
                        'label' => 'Testing, Tools, and Frameworks Zone',
                        'description' => '',
                        'slug' => 'testing-tools-and-frameworks',
                        'url' => 'https://feeds.dzone.com/testing-tools-and-frameworks'
                    ],
                    [
                        'label' => 'Tools',
                        'description' => '',
                        'slug' => 'tools',
                        'url' => 'https://feeds.dzone.com/tools'
                    ],
                    [
                        'label' => 'Web Dev',
                        'description' => 'Latest articles from Web Dev Zone',
                        'slug' => 'web-dev',
                        'url' => 'http://feeds.dzone.com/webdev'
                    ],
                ],
            ],
        ];
    }

}
